# Generated by Django 4.1.2 on 2022-10-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_stage', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('country', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=32)),
                ('employees', models.IntegerField()),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_seed', to='company.fundingstage')),
            ],
        ),
    ]
